Feature/resonant axis calculator
4xxi/resonances-fortran pull request #1
Opened 2017-02-07 16:20 UTC by idovgalyov

Description of the current version of the resonance calculator.

This version works with 2-body resonances for now.
The program contains several modules, main source file and makefile.

The modules are:
global_parameters - containing constants, simple functions and common parameters
id_matrix - module for managing id. matrices (creating, saving in memory, cleaning, etc.)
resonant_axis - calculates resonant values of semimajor axes needed for creating id. matrices (in files)
resonance_finder - finds possible resonances for an asteroid

The main source file "main.f95" is currently using for getting results by "resonance_finder" module.
Makefile is used for compiling and getting executable file "axis".
To run the program use the command `./axis asteroid a delta`, where:
- "asteroid" is an asteroid name
- "a"  - it's semimajor axis (in AU)
- "delta"  - semisize of searching interval (in AU)

The program finds possible resonances and places them in "asteroid.rpin" file.
It also creates files with id. matrices and checks possibility or their use.

Some comments:
- maximum resonance order currently gives as a parameter in "global_parameters" module.
- tests for .fun files are still in progress
- "main.f95" can be changed for testing some procedures if needed.

2017-02-07 20:46 UTC, smirik requested changes
Added comments. Most of them are related to the unit tests, but there are also few comments related to the functions / sub-routines.

2017-02-07 20:46 UTC, smirik commented on axis/global_parameters.f95
> +integer function planet_id(s)
This function requires a unit test.

2017-02-07 20:46 UTC, smirik commented on axis/global_parameters.f95
> +function planet_name(i) result(s)
This function requires a unit test.

2017-02-07 20:46 UTC, smirik commented on axis/global_parameters.f95
> +             write(*,*)'Warning! Detected incorrect planet id, be careful.'
Better to say:
"Error! The planet id must be between 1 and 9."

2017-02-07 20:46 UTC, smirik commented on axis/global_parameters.f95
> +            write(*,*)'Warning! Detected incorrect planet name, be careful.'
Better to say:
"Error! Planet name must be one from the list: MERCURY, VENUS, EARTHMOO, MARS, JUPITER, SATURN, URANUS, NEPTUNE, PLUTO".

2017-02-07 20:46 UTC, smirik commented on axis/global_parameters.f95
> +integer function nod(a,b)
This function requires a unit test.
Also, don't you think that the function requires too much variables? 
Here are the examples of more easy implementations:
https://users.soe.ucsc.edu/~pohl/FORTRAN/Chfor/gcd.for

2017-02-07 20:46 UTC, smirik commented on axis/id_matrix.f95
> +integer function get_idmatrix_2body_status(pl_id)
This function requires a unit test.

2017-02-07 20:46 UTC, smirik commented on axis/global_parameters.f95
> +integer function nod(a,b)
Also it should be named gcd, not nod.

2017-02-07 20:46 UTC, smirik commented on axis/id_matrix.f95
> +    if(allocated(idmatrix_2body(pl_id)%matrix)) then
Could you please explain what happens here?

2017-02-07 20:46 UTC, smirik commented on axis/id_matrix.f95
> +        s=0
Isn't it a good idea to use return here instead of continuing the program execution?

2017-02-07 20:46 UTC, smirik commented on axis/id_matrix.f95
> +            s=-1
See the comment above. Isn't return a good option?

2017-02-07 20:46 UTC, smirik commented on axis/id_matrix.f95
> +    type(idmrow_2body),dimension(1000):: matrix
Why the dimension is 1000.

2017-02-07 20:46 UTC, smirik commented on axis/resonance_finder.f95
> +subroutine get_all_possible_resonances_2body(asteroid,a,delta)
Why is it subroutine, not a function?

2017-02-07 20:46 UTC, smirik commented on axis/resonance_finder.f95
> +            write(*,*) 'Not found idmatrix in memory - try to find corresponding file...'
Please replace the text with the following:
"Cannot find the identification matrix in the memory. Trying to load from the file".

2017-02-07 20:46 UTC, smirik commented on axis/resonance_finder.f95
> +            open(unit=un,file='id_matrix_'//trim(pl_name)//'.dat',action='read',iostat=s)
Why do you do here the loading manually, not via invocation of the function: add_idmatrix_2body.

2017-02-07 20:46 UTC, smirik commented on axis/resonant_axis.f95
> +subroutine make_id_matrix_2body(pl_name,max_order)
make -> build
This subroutine should have a unit test (that the file has been created & it is correct).

2017-02-07 20:46 UTC, smirik commented on axis/resonant_axis.f95
> +subroutine make_id_matrix_2body(pl_name,max_order)
Why this subroutine is in resonant_axis.f95, not in id_matrix?

2017-02-07 20:46 UTC, smirik commented on axis/resonant_axis.f95
> +        do m=-1,-m1-max_order,-1
Why m is negative only? 
5J+2 — IMO, normal resonance, is not it? In your case we check only 5J-2, right?

2017-02-07 20:46 UTC, smirik commented on axis/resonant_axis.fun
> +    assert_equal_within(,2.8253d0,1d-3)
Add, also, please, well-known case for Kirkwood gaps.

2017-02-08 11:41 UTC, smirik commented on axis/resonance_finder.f95
> +subroutine get_all_possible_resonances_2body(asteroid,a,delta)
OK

2017-02-08 14:58 UTC, idovgalyov commented on axis/global_parameters.f95
> +            write(*,*)'Warning! Detected incorrect planet name, be careful.'
Done

2017-02-08 14:59 UTC, idovgalyov commented on axis/global_parameters.f95
> +             write(*,*)'Warning! Detected incorrect planet id, be careful.'
Done

2017-02-08 15:01 UTC, idovgalyov commented on axis/global_parameters.f95
> +integer function nod(a,b)
Refreshed the function, named gcd, deleted 1 variable and modified the algorithm.

2017-02-08 15:03 UTC, idovgalyov commented on axis/id_matrix.f95
> +        s=0
Modified this function for using "return" with no conflicts with Fortran specifications.

2017-02-08 15:05 UTC, idovgalyov commented on axis/id_matrix.f95
> +    type(idmrow_2body),dimension(1000):: matrix
Fixed this.
The method I've described.
Thought it would be acceptable.

2017-02-08 15:06 UTC, idovgalyov commented on axis/resonance_finder.f95
> +            write(*,*) 'Not found idmatrix in memory - try to find corresponding file...'
Done

2017-02-08 15:09 UTC, idovgalyov commented on axis/resonance_finder.f95
> +            open(unit=un,file='id_matrix_'//trim(pl_name)//'.dat',action='read',iostat=s)
Justifiable.
Applied this subroutine.

2017-02-08 15:10 UTC, idovgalyov commented on axis/resonant_axis.f95
> +subroutine make_id_matrix_2body(pl_name,max_order)
Renamed and moved to "id_matrix" module.
There are still questions about unit test...

2017-02-08 15:12 UTC, idovgalyov commented on axis/resonant_axis.f95
> +        do m=-1,-m1-max_order,-1
Found some precedents.
Left as is for now.

2017-02-08 15:12 UTC, idovgalyov commented on axis/resonant_axis.fun
> +    assert_equal_within(,2.8253d0,1d-3)
Done

2017-02-08 15:13 UTC, idovgalyov commented on axis/id_matrix.f95
> +integer function get_idmatrix_2body_status(pl_id)
There are still questions about unit test...

2017-02-08 21:15 UTC, smirik approved these changes

2017-02-08 21:16 UTC, smirik requested changes
The tests are still not working, even if replace .f95 with .f90. The issue is in REAL(4) vs REAL(8). Need to be fixed before the commit.

2017-02-08 21:18 UTC, smirik commented on axis/global_parameters.fun
> +    g=gcd(a1,b1)
IMO, additional things.
Why not to check directly?
`assert_equal(12,gcd(60,12))`?
Why do you create an extra variables?

2017-02-08 21:19 UTC, smirik commented on axis/id_matrix.f95
> +! TO DO - here is a weakness of the program with uncertainity of matrix length - need a cure
Why the code is commented?

2017-02-08 21:23 UTC, smirik requested changes
See the comments

2017-02-08 21:23 UTC, smirik commented on axis/id_matrix.fun
> +! assert_true(expression)
These strings with the comments were added initially as examples. Please remove them!

2017-02-08 21:23 UTC, smirik commented on axis/global_parameters.fun
> +! assert_true(expression)
These strings with the comments were added initially as examples. Please remove them!

2017-02-08 21:23 UTC, smirik commented on axis/id_matrix.f95
> +! TO DO - here is a weakness of the program with uncertainity of matrix length - need a cure
Why the code is commented?

2017-02-08 21:23 UTC, smirik commented on axis/global_parameters.fun
> +    g=gcd(a1,b1)
IMO, additional things.
Why not to check directly?
`assert_equal(12,gcd(60,12))`?
Why do you create an extra variables?

2017-02-08 21:23 UTC, smirik commented on axis/main.f95
> +program resonant_axis_calculator
Just FYI: if I run the command without the arguments, it shows the error. But how can I find the arguments I should put?

2017-02-08 21:23 UTC, smirik commented on axis/resonance_finder.f95
> +            write (*, *) 'No founded idmatrix for ', pl_name, '!'
'No founded idmatrix' -> 'idmatrix was not found'

2017-02-09 12:09 UTC, idovgalyov commented on axis/id_matrix.fun
> +! assert_true(expression)
Done

2017-02-09 12:13 UTC, idovgalyov commented on axis/id_matrix.f95
> +! TO DO - here is a weakness of the program with uncertainity of matrix length - need a cure
Here I decided to use more stable file-measuring method.
I came to decision that it wouldn't be a significant fall of performance.

2017-02-09 12:14 UTC, idovgalyov commented on axis/main.f95
> +program resonant_axis_calculator
Provided Readme with description of how to lsunch the current version.

2017-02-09 12:15 UTC, idovgalyov commented on axis/resonance_finder.f95
> +            write (*, *) 'No founded idmatrix for ', pl_name, '!'
Done

2017-02-09 12:36 UTC, smirik approved these changes

2017-02-09 12:39 UTC, merged